### ISSUE TITLE
Chameleon error when throughput with string w/range setting in config

### ISSUE THREAD

**Issue by jhao0117** [timeplus-io/chameleon#35]
```
INFO[0001]/home/ubuntu/chameleon/generator/plugins/timeplus/observer.go:186 github.com/timeplus-io/chameleon/generator/plugins/timeplus.(*TimeplusObserver).observeThroughput() stop observing throughput
panic: interface conversion: interface {} is []interface {}, not map[string]interface {}

goroutine 179 [running]:
github.com/timeplus-io/chameleon/generator/plugins/timeplus.(*TimeplusObserver).observeThroughput.func1({0xf08700?, 0xc000638168?})
	/home/ubuntu/chameleon/generator/plugins/timeplus/observer.go:174 +0x145
github.com/reactivex/rxgo/v2.(*ObservableImpl).ForEach.func1({0x129f878, 0xc00012a000}, 0xc0004c2120)
	/home/ubuntu/chameleon/pkg/mod/github.com/reactivex/rxgo/v2@v2.5.0/observable_operator.go:1172 +0x162
created by github.com/reactivex/rxgo/v2.(*ObservableImpl).ForEach
	/home/ubuntu/chameleon/pkg/mod/github.com/reactivex/rxgo/v2@v2.5.0/observable_operator.go:1181 +0x1ac
exit status 2
ubuntu@ip-172-31-50-206:~/chameleon/generator$
```
[timeplus_throughput.yaml.tar.gz](https://github.com/timeplus-io/chameleon/files/9837603/timeplus_throughput.yaml.tar.gz)

**Comment by jhao0117** [comment]
verified in latest chameleon.

**Comment by jovezhong** [comment]
(Jove Github Bot) added it to the current sprint.
